config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'
  devise_for :users
  resources :users, only: [:show, :edit, :update]

  namespace :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end

  resources :prototypes do
    resources :comments, only: :create
  end

  resources :likes, only:[:create, :destroy]
  resources :tags, only:[:index, :show], param: :name
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).newest_order.page(params[:page]).per(Prototype::NUMBER_OF_DISPLAYED_PROTOTYPES)
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).from_highest_count.page(params[:page]).per(Prototype::NUMBER_OF_DISPLAYED_PROTOTYPES)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.includes(:user, :tags).page(params[:page]).per(Prototype::NUMBER_OF_DISPLAYED_PROTOTYPES)
  end

  def show
    @comments = @prototype.comments.includes(:user)
  end

  def new
    @placeholders = %W(Web\sdesign UI Application)
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)

    if @prototype.save
      redirect_to prototypes_path, notice: "Succeeded to publish your prototype"
    else
      redirect_to new_prototype_path, alert: "Failed to publish your prototype"
    end
  end

  def edit
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to prototypes_path, notice: "Succeeded to update your prototype"
    else
      redirect_to edit_prototype_path, alert: "Failed to update your prototype"
    end
  end

  def destroy
    unless @prototype.created_by?(current_user)
      redirect_to prototypes_path, alert: "Cannot delete other's prototype" and return
    end

    if @prototype.destroy
      redirect_to prototypes_path, notice: "Succeeded to delete your prototype" and return
    else
      redirect_to prototypes_path, alert: "Failed to delete your prototype" and return
    end
  end

  private
  def prototype_params
    params.require(:prototype).permit(:name, :catch_copy, :concept, :user_id, tag_list: [], captured_images_attributes: [:id, :image, :status])
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/views/prototypes/_logo_navbar.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      = content_tag :ul, class: "nav nav-pills col-lg-11" do
        = content_tag :li, role: "presentation", class: "active", id: "popular" do
          = link_to "Popular PROTO", prototypes_popular_index_path, remote: true
        = content_tag :li, role: "presentation", id: "newest" do
          = link_to "Newest PROTO", prototypes_newest_index_path, remote: true
        = content_tag :li, role: "presentation", class: "nav-button__right" do
          = link_to "View tags", tags_path, class: "btn btn-default col-lg-11"

app/views/prototypes/_pagination.html.haml
= paginate prototypes, remote: true

app/views/prototypes/_prototype.html.haml
- user = prototype.user
.col-sm-4.col-md-3.proto-content
  - if user_signed_in?
    .dropdown.drop_menu_location
      = button_tag class: "btn btn-default dropdown-toggle", "data-toggle": "dropdown", id: "dropdownMenu", "aria-expanded": true do
        ACTION
      = content_tag :ul, "aria-labelledby": "dropdownMenu1", class: "dropdown-menu" do
        = content_tag :li do
          = link_to "Edit", edit_prototype_path(prototype)
        = content_tag :li do
          = link_to "Delete", prototype_path(prototype), method: :delete
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag(prototype.main_image)
      .caption
        = content_tag :h3, prototype.name
        .proto-meta
          .proto-user
            = link_to user_path(user) do
              = "by #{user.name}"
          .proto-posted
            = prototype.created_at
        %ul.proto-tag-list.list-inline
          = render partial: "tags/tag", collection: prototype.tags

app/views/prototypes/_sub_image.html.haml
%li.sub-image-item.col-md-4
  = image_tag(sub_image.image ,class: 'img-responsive')

app/views/prototypes/_sub_image_edit_form.html.haml
%li.sub-image-item.col-md-4
  .image-upload
    = image_tag image_form.object.image
    = image_form.file_field :image, class: "js-image-file"
    = image_form.hidden_field :status, value: "sub"

app/views/prototypes/_sub_image_form.html.haml
%li.list-group-item.col-md-4
  .image-upload
    = image_form.file_field :image, class: "js-image-file"
    = image_form.hidden_field :status, value: "sub", class: "js-image-hidden"

app/views/prototypes/_sub_image_new_form.html.haml
%li.sub-image-item.col-md-4
  .image-upload
    %img
    = image_form.file_field :image, class: "js-image-file"
    = image_form.hidden_field :status, value: "sub"

app/views/prototypes/_sub_image_plus.html.haml
%li.sub-image-item.col-md-4#js-image-plus
  .image-upload-plus
    %span +

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :name ,placeholder: "Title", class: "proto-new-title"
      .row
        = f.fields_for :captured_images, @prototype.captured_images.main.first do |image_form|
          .cover-image-upload.col-md-12
            = image_tag @prototype.main_image
            = image_form.file_field :image, class: "js-image-file"
            = image_form.hidden_field :status, value: "main"
          .col-md-12.proto-sub-list
            %ul#js-proto-sub-list
              = f.fields_for :captured_images, @prototype.sub_images do |image_form|
                = render "sub_image_edit_form", image_form: image_form
              - if @prototype.sub_images.length < Prototype::MAXIMUM_NUMBER_OF_SUB_IMAGES_IN_PROTOTYPE
                = render "sub_image_plus"
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            = render partial: "tags/tag_form", collection: @prototype.tags, as: :tag
        = f.hidden_field :user_id, value: current_user.id
      .row.text-center.proto-btn
        = f.submit "Publish", class: "button btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
= render "logo_navbar"
.container.proto-list
  .row
    = render partial: "prototype", collection: @prototypes
.text-center#pagination
  = render "pagination", prototypes: @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :name ,placeholder: "Title", class: "proto-new-title"
      .row
        = f.fields_for :captured_images do |image_form|
          .cover-image-upload.col-md-12
            %img
            = image_form.file_field :image, class: "js-image-file"
            = image_form.hidden_field :status, value: "main"
          .col-md-12.proto-sub-list
            %ul#js-proto-sub-list
              - Prototype::NUMBER_OF_SUB_IMAGES_IN_NEW_PROTOTYPE_FORM.times do
                = f.fields_for :captured_images do |image_form|
                  = render "sub_image_new_form", image_form: image_form
              = render "sub_image_plus"
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            - Prototype::NUMBER_OF_TAGS_IN_A_PROTOTYPE.times do |i|
              = render "tags/tag_new_form", tag_list: @prototype.tag_list, placeholders: @placeholders, i: i
        = f.hidden_field :user_id, value: current_user.id
      .row.text-center.proto-btn
        = f.submit "Publish", class: "button btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
- user = @prototype.user
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(user) do
            = image_tag user.avatar, alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", style: "width: 64px; height: 64px;", class: "media-object"
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.name
          .proto-user
            =link_to "by #{user.name}", user_path(user)
            %span.degree
              = user.occupation

    .col-md-6.text-right#like
      - if user_signed_in?
        - if @prototype.liked_by?(current_user)
          = render "likes/like", prototype: @prototype
        - else
          = render "likes/unlike", prototype: @prototype
      - else
        = render "likes/like_user_not_signed_in", prototype: @prototype
  .row
    .col-md-9
      = image_tag(@prototype.main_image ,class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        = render partial: "sub_image", collection: @prototype.sub_images

  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: "tags/tag", collection: @prototype.tags
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = "(#{@prototype.comment_num})"
    .col-md-8.comments-list
      = render partial: "comments/comment", collection: @comments
    - if user_signed_in?
      = form_for [@prototype, @comments.new] , remote: true do |f|
        %h4.col-md-8 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :text, placeholder: "Your comments", rows: "3", class: "form-control", id: "comment-text"
          .form-group.col-md-2
            %button.btn.btn-primary Comment