config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'
  devise_for :users
  resources :users, only: [:show, :edit, :update]

  namespace :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end

  resources :prototypes do
    resources :comments, only: :create
  end

  resources :likes, only:[:create, :destroy]
  resources :tags, only:[:index, :show], param: :name
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :prototype, counter_cache: :like_count
  belongs_to :user

  validates :prototype_id, uniqueness: { scope: :user_id }, presence: true, numericality: { only_integer: true }
  validates :user_id, uniqueness: { scope: :prototype_id }, presence: true, numericality: { only_integer: true }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_prototype, only: [:create, :destroy]

  def create
    @prototype.likes.create(user_id: current_user.id)
  end

  def destroy
    like = @prototype.likes.find_by(user_id: current_user.id)
    like.destroy if like.present?
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/views/likes/_like.html.haml
%button.btn.btn-default
  = link_to like_path(prototype.id), method: "delete", remote: true do
    = image_tag("icon_red_heart.svg")
    Like
    %span.num
      = prototype.like_count

app/views/likes/_like_user_not_signed_in.html.haml
%button.btn.btn-default
  = link_to new_user_session_path do
    = image_tag("icon_heart.svg")
    Like
    %span.num
      = prototype.like_count

app/views/likes/_unlike.html.haml
%button.btn.btn-default
  = link_to likes_path(id: prototype.id), method: "post", remote: true do
    = image_tag("icon_heart.svg")
    Like
    %span.num
      = prototype.like_count

app/views/likes/create.js.haml
$("#like").html("#{ j(render "likes/like", prototype: @prototype)}")

app/views/likes/destroy.js.haml
$("#like").html("#{ j(render "likes/unlike", prototype: @prototype)}")