config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'
  devise_for :users
  resources :users, only: [:show, :edit, :update]

  namespace :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end

  resources :prototypes do
    resources :comments, only: :create
  end

  resources :likes, only:[:create, :destroy]
  resources :tags, only:[:index, :show], param: :name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find_by(name: tag_params[:name])
    @prototypes_count = Prototype.tagged_with(@tag).length
    @prototypes = Prototype.tagged_with(@tag.name).includes(:user, :tags).page(@tag.name).per(Prototype::NUMBER_OF_DISPLAYED_PROTOTYPES)
  end

  private
  def tag_params
    params.permit(:name)
  end
end

app/views/tags/_tag.html.haml
= content_tag :li do
  = link_to tag_path(tag.name) , class: "btn btn-default" do
    = tag.name

app/views/tags/_tag_form.html.haml
.col-md-3
  = text_field_tag 'prototype[tag_list][]', tag

app/views/tags/_tag_new_form.html.haml
.col-md-3
  = text_field_tag 'prototype[tag_list][]', tag_list, placeholder: placeholders[i]

app/views/tags/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-body
        = content_tag :h4, class: "media-heading", id: "top-aligned-media" do
          Tag List
          %span.label.label-default.project-number
            = @tags.length
            %i Projects
  = content_tag :ul, class: "proto-tag-list list-inline" do
    = render partial: "tag", collection: @tags

app/views/tags/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-body
        = content_tag :h4, class: "media-heading", id: "top-aligned-media" do
          = @tag.name
          %span.label.label-default.project-number
            = @prototypes_count
            %i Projects
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center#pagination
  = paginate @prototypes