config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'
  devise_for :users
  resources :users, only: [:show, :edit, :update]

  namespace :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
  end

  resources :prototypes do
    resources :comments, only: :create
  end

  resources :likes, only:[:create, :destroy]
  resources :tags, only:[:index, :show], param: :name
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  - key = "success" if key == "notice"
  - key = "danger" if key == "alert"
  = content_tag(:div, value, class: "alert alert-#{key}" )

app/views/layouts/_footer.html.haml
.container
  %footer
    = content_tag :p do
      &copy; PROTO SPACE 2017.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            =link_to current_user.name, "aria-expanded": "false", "data-toggle": "dropdown", class: "dropdown-toggle" do
              = current_user.name
              %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li
                  =link_to "My Page", user_path(current_user)
                %li
                  =link_to "Profile Edit", edit_user_path(current_user)
                %li
                  =link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              =link_to "New Proto", new_prototype_path
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              =link_to "Get Started", new_user_session_path

app/views/layouts/_logo_navbar.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      = content_tag :ul, class: "nav nav-pills col-lg-11" do
        = content_tag :li, class: "active", role: "presentation" do
          = link_to "Popular PROTO", popular_index_path
        = content_tag :li, role: "presentation" do
          = link_to "Newest PROTO", newest_index_path
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv": "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container
      =render 'layouts/flash_messages'
    = yield
    = render "layouts/footer"